### ISSUE TITLE
Msgpack not found

### ISSUE THREAD

**Issue by Botox200** [subreption/hackrf_sweeper#1]
Compiling issues. 

So in order to avoid compiling issues at 
`cmake ..`
install  
` sudo apt install libmsgpack-dev`

**Comment by ghost** [comment]
I had this issue too. Updating README.md would be nice.

**Comment by sbrptdev2** [comment]
Updated the README. Do note that the library itself does not depend on msgpack. Only the demo ZMQ publisher does. I will review the CMake rules, as it should have been automatically ignored if the library wasn't available.

Thanks for the report!
