### ISSUE TITLE
ZMQ subscriber doesn't recv data

### ISSUE THREAD

**Issue by ghost** [subreption/hackrf_sweeper#2]
Hi,

I created the server-key file and started the applications as suggested in the README.md file. However, ZMQ consumer thread in the demo/hackrf_sweeper_zmq2plot.py doesn't poll any data. Do you have any suggestions for finding the connection error?

**Comment by sbrptdev2** [comment]
Hi,


Could you provide the full output (stdout/stderr) of both the server and hackrf_sweeper_zmq2plot.py? If you are running something like Open Snitch or similar, please also check you allowed the ZMQ socket to bind.

Also: use hackrf_sweeper (the standalone program, to confirm the library is functioning properly with your HackRF), and paste the first 200 lines (pipe to head -n200 for example, enable ASCII tabular output).
