### ISSUE TITLE
[BUG] System msgpack not found

### ISSUE THREAD

**Issue by zwillikon** [subreption/hackrf_sweeper#6]
I know that msgpack is only needed for the demo as per https://github.com/subreption/hackrf_sweeper/issues/1

On my system there are _/usr/lib/cmake/msgpack-c/msgpack-c-config.cmake_ and _/usr/lib/cmake/msgpack-cxx/msgpack-cxx-config.cmake_

```
  Could not find a package configuration file provided by "Msgpack" with any
  of the following names:

    MsgpackConfig.cmake
    msgpack-config.cmake
```

Shall I symlink to the C version for sweeper?

**Comment by sbrptdev2** [comment]
This is odd. What is your base OS? I will try to verify and add an additional CI target if there is a docker base image for it.

Meanwhile, it should be sufficient to symlink/create the expected CMake file, as you suggested, but this is not ideal as your package manager should be already conforming to the expected naming scheme.

**Comment by zwillikon** [comment]
ArchLinux

**Comment by sbrptdev2** [comment]
Could you paste the contents of your `/usr/lib/cmake/msgpack-c/msgpack-c-config.cmake `?

**Comment by zwillikon** [comment]
```
####### The input file was msgpack-c-config.cmake.in                            ########

get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)

# Use original install prefix when loaded through a "/usr move"
# cross-prefix symbolic link such as /lib -> /usr/lib.
get_filename_component(_realCurr "${CMAKE_CURRENT_LIST_DIR}" REALPATH)
get_filename_component(_realOrig "/usr/lib/cmake/msgpack-c" REALPATH)
if(_realCurr STREQUAL _realOrig)
  set(PACKAGE_PREFIX_DIR "/usr")
endif()
unset(_realOrig)
unset(_realCurr)

macro(set_and_check _var _file)
  set(${_var} "${_file}")
  if(NOT EXISTS "${_file}")
    message(FATAL_ERROR "File or directory ${_file} referenced by variable ${_var} does not exist !")
  endif()
endmacro()

macro(check_required_components _NAME)
  foreach(comp ${${_NAME}_FIND_COMPONENTS})
    if(NOT ${_NAME}_${comp}_FOUND)
      if(${_NAME}_FIND_REQUIRED_${comp})
        set(${_NAME}_FOUND FALSE)
      endif()
    endif()
  endforeach()
endmacro()

####################################################################################

include(CMakeFindDependencyMacro)

if(NOT TARGET msgpack-c AND NOT TARGET msgpack-c-static)
  include("${CMAKE_CURRENT_LIST_DIR}/msgpack-c-targets.cmake")
endif()
```

**Comment by sbrptdev2** [comment]
Please check commit https://github.com/subreption/hackrf_sweeper/commit/e39e103b8813e82de2cdcd0dad50491c765625da 

Update your repo, and let me know if that resolves the issue for ArchLinux.

**Comment by sbrptdev2** [comment]
Reported fixed.

**Comment by hankaiwen** [comment]
Hi - Love what hackrf_sweeper can do but I got this same bug on Ubuntu 24.1 Oracular - thanks I'm a nube. Cheers, Kevin
________________________________________________________________________________________________________
CMake Error at CMakeLists.txt:108 (find_package):
  By not providing "Findmsgpack.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "msgpack", but
  CMake did not find one.

  Could not find a package configuration file provided by "msgpack" with any
  of the following names:

    msgpackConfig.cmake
    msgpack-config.cmake

  Add the installation prefix of "msgpack" to CMAKE_PREFIX_PATH or set
  "msgpack_DIR" to a directory containing one of the above files.  If
  "msgpack" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by sbrptdev2** [comment]
I have closed the issue as we cannot offer support/workarounds for every distribution that decides to break how msgpack is handled. Have a look at how our automated build testing is setup. README also shows the build dependencies needed. If Ubuntu (or any other distro) breaks things, you need to file a bug with them.

**Comment by hankaiwen** [comment]
OK thanks

**Comment by stigl-cc** [comment]
For anyone coming here with the same issue on archlinux, install `msgpack-c` from pacman modify the CMakeLists.txt file and replace all Msgpack with Msgpack-c, works just fine.
