### ISSUE TITLE
[BUG] Installation Issue, libczmq "libsystemd-dev"

### ISSUE THREAD

**Issue by SaturnsVoid** [subreption/hackrf_sweeper#7]
Trying to install the prerequisites for the program i am getting the following issues on Parrot OS (Security) 6.2 lorikeet.

When running 
"sudo apt-get install libhackrf-dev libczmq-dev libzmq5 libmsgpack-dev"
I get the following error:
"The following packages have unmet dependencies:
   libsystemd-dev  :  Depends : libsystemd0 (= 252.31-1~deb12u1)

E: Unable to correct problems, you have held broken packages.
"

Tried updating sources and issue still persists.

**Comment by sbrptdev2** [comment]
Please do not report OS-specific problems, this is clearly a problem with either your specific installation of Parrot OS, Parrot OS itself (broken dependencies), or both.
